config/routes.rb
Nfy::Application.routes.draw do
  get '/_alive.txt', to: proc { [200, {}, ['alive']] }

  get 'sitemap.xml' => 'home#sitemap', format: :xml, as: :sitemap

  resources :lists

  resources :categories

  devise_for :users, path: '', path_names:
  {
    sign_in: 'login',
    sign_out: 'logout',
    sign_up: 'register'
  }

  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users/:id' => 'devise/registrations#update', :as => 'user_registration'
    delete 'users/:id' => 'devise/registrations#destroy', :as => 'destroy_user_registration'
  end

  resources :note do
    patch 'copy', on: :collection
  end

  resources :onboarding, only: [:update]
  resources :support, only: %i[index create]

  root 'home#index'

  get '/dashboard' => 'dashboard#index'

  get '/user' => 'user#index'

  get '/tos' => 'public#tos'
  get '/privacy-policy' => 'public#privacy_policy'

  get '/bot' => 'public#bot'

  authenticate :user, ->(u) { u.admin? } do
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  get '/invitation_request', to: 'invitation_requests#create'
  post '/invitation_request', to: 'invitation_requests#update', as: 'invitation_requests'

  get '/public', to: 'public_notes#index', as: :public_notes

end

app/views/shared/_analytics.html.haml
- if Rails.env == 'production'
  %script
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', "#{APP.analytics_code}", 'auto');
    ga('set', 'forceSSL', true);
    ga('require', 'displayfeatures');
    - unless defined? silent
      ga('send', 'pageview');

app/views/shared/_detail_metas.html.haml
%meta(name="description" content="#{print_content_for(:description, t('home.metas.description'))}")

app/views/shared/_detail_quick_signup.haml
.container
  .col-md-12
    = render 'shared/quick_signup'

app/views/shared/_footer.html.haml
.container.credits
  .text-center.col-md-12
    %p
      #{t('layout.footer.copyright')} © #{Time.now.year} #{APP.app_name} - #{t('layout.footer.all_rights_reserved')} - #{link_to(t('terms_of_use'), tos_path)} - #{link_to(t('privacy_policy'), privacy_policy_path)} - <a href="https://github.com/ainformatico/nofity">#{t('layout.footer.open_source')}</a>
    - if user_signed_in?
      %p
        #{APP.git_hash}

app/views/shared/_header.html.haml
- cache(cache_name('app_header')) do
  %nav.navbar.navbar-default(role="navigation")
    .container
      .container-fluid
        .navbar-header
          %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".bs-navbar-collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to APP.app_name, dashboard_path, class: 'navbar-brand'
        .collapse.navbar-collapse.bs-navbar-collapse
          %ul.nav.navbar-nav.col-md-4
            %li
              = link_to t('note.all'), note_index_path, id: 'notes-list'
            %li
              = link_to t('note.public'), public_notes_path, id: 'notes-public'
          %ul.nav.navbar-nav.col-lg-5.col-lg-push-4.col-md-3.col-md-push-4.col-sm-4.col-sm-push-6
            %li.dropdown
              %a(href="#" id="user-profile" data-toggle="dropdown" data-bypass="true" class="dropdown-toggle")
                = t('header.profile')
                %i.caret
              %ul.dropdown-menu(role="menu")
                %li
                  = link_to t('header.edit_profile'), edit_user_registration_path, data: {bypass: true}
                %li.divider
                %li
                  = link_to t('header.new_invitation'), new_user_invitation_path, data: {bypass: true}
                %li.divider
                %li
                  = link_to t('header.support'), support_index_path, data: {bypass: true}
            %li
              = link_to t('header.sign_out'), destroy_user_session_path, data: {bypass: true}

app/views/shared/_metas.html.haml
- cache(cache_name('metas')) do
  %meta(charset="utf-8")
  %meta(name="author" content="#{APP.author}")
  %meta(name="viewport" content="width=device-width, initial-scale=1.0")
  %meta(content="index, follow" name="robots")
  %meta(name="google-site-verification" content="LYFmUfjvH4MDHaLGoHGVVVJKNgTR_xoZjdSQoSoH5t4")

app/views/shared/_public_metas.html.haml
- cache(cache_name('public_metas')) do
  %meta(name="description" content="#{t('home.metas.description')}")
  %meta(name="keywords" content="#{t('home.metas.keywords')}")

app/views/shared/_quick_signup.haml
- cache(cache_name('quick_signup')) do
  #about-us
    #cta
      .col-md-12
        .wrapper.clearfix.project
          %h4
            = t('cfa.join_us')
          %p
            = link_to t('cfa.request_invitation'), invitation_request_path, class: 'button button-small'